#!/bin/bash

# osxapp_vers 1.2
# Get product name, product version and build version of [Mac] OS X
# from "Install*OS X*.app" resp. from "Mac OS X install DVD"
#
# Copyright 2015-2016 Johann N. Loefflmann
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Explicitly set the PATH
PATH="/sbin:/usr/sbin:/bin:/usr/bin"

# Prints one token from a xml content, prints nothing if there is no match
# Params: $1: xml content, $2: key in the xml, $3: key name in the output
function print_xml_token {
    # Extract the token name from the xml
    if [[ "$1" =~ \<key\>$2\</key\>[[:space:]]*\<string\>([^\<]+)\</string\> ]]; then
        printf "$3:\t%s\n" ${BASH_REMATCH[1]}
    fi
}

# Prints ProductName, ProductVersion and BuildVersion from a xml content
# Params: $1: the name of the xml file
function print_xml_info {
    # Read the xml
    XMLCONTENT=$(<"$1")

    print_xml_token "$XMLCONTENT" 'ProductName' 'ProductName'
    print_xml_token "$XMLCONTENT" 'ProductVersion' 'ProductVersion'
    print_xml_token "$XMLCONTENT" 'ProductBuildVersion' 'BuildVersion'
    printf "\n"
}

# Supported OS names for the "Install *OS X <name>.app",
# update list if applicable
SUPPORTED_OS=('El Capitan' 'Yosemite' 'Mavericks' 'Mountain Lion' 'Lion')

# Do we want verbose output?
if [ -z $DEBUG ]; then
    DEBUG=/dev/null
else
    DEBUG=/dev/stdout
fi

# Backup and set the Internal Field Separator (IFS) to newline,
# because there are blanks in the filename called "Install OS X *.app"
IFS_BACKUP=$IFS
IFS=$'\n'

# Update SUPPORTED_OS, because $IFS has changed
SUPPORTED_OS=$(printf "%s\n" ${SUPPORTED_OS[@]})

if [ $# = 0 ]; then
    # No args have been given
    # Find any OS X installers in /Applications
    FILES=$(ls -ld1 /Applications/Install\ *OS\ X\ *.app 2>/dev/null)
else
    # Use the program arguments as the input
    FILES=$(printf "%s\n" $@)
fi

# Error message if there is no installer
if [ -z "$FILES" ]; then
    printf "There is no \"Install *OS X *.app\" in /Applications\n" > $DEBUG
else
    for FILE in $FILES; do
        # print the app folder
        printf "%s:\n" "$FILE"

        # Remove everything from the end including . (non-greedy)
        # In other words, .app or .app/ will be removed from the end
        APPNAME=${FILE%.*}
        # Remove everything from the beginning including /
        OSNAME=${APPNAME##*/}
        # Remove everything from the beginning including "OS X "
        OSNAME=${APPNAME##*OS\ X\ }
        # Re-add the .app suffix
        APPNAME="$APPNAME.app"

        if [ -z $NOCHECK ]; then
            # NOCHECK is not set
            # Is the .app supported by this script?
            SUPPORTED=0
            for OS in $SUPPORTED_OS
            do
                if [ "$OSNAME" = "$OS" ]; then
                    SUPPORTED=1
                fi
            done
        else
            SUPPORTED=1
        fi

        if [ $SUPPORTED -eq 0 ]; then
            printf "%s is not supported by this script. Set NOCHECK to bypass this check.\n" $OSNAME
        else
            # Mount the InstallESD.dmg
            hdiutil attach "$APPNAME/Contents/SharedSupport/InstallESD.dmg" \
                -noverify -nobrowse -mountpoint /Volumes/InstallESD.$$ > $DEBUG

            # Mount the BaseSystem.dmg
            hdiutil attach "/Volumes/InstallESD.$$/BaseSystem.dmg" \
                -noverify -nobrowse -mountpoint /Volumes/BaseSystem.$$ > $DEBUG

            # call sw_vers in the changed root environment
            # sudo chroot "/Volumes/BaseSystem.$$" /usr/bin/sw_vers

            # Read the xml and print info
            print_xml_info "/Volumes/BaseSystem.$$/System/Library/CoreServices/SystemVersion.plist"

            # Unmount again in reverse order
            hdiutil detach "/Volumes/BaseSystem.$$" > $DEBUG
            hdiutil detach "/Volumes/InstallESD.$$" > $DEBUG
        fi
    done
fi

# And now let's do it for any mounted Mac OS X Install CD/DVD images
# (Mac OS X 10.0 Cheetah) - Mac OS X 10.6 Snow Leopard)
#
if [ $# = 0 ]; then
    # No args have been given
    # Find any mounted Mac OS X Install CD/DVD images in /Volumes
    FILES=$(ls -ld1 /Volumes/Mac\ OS\ X\ Install\ * 2>/dev/null)

    # Message if there are no mounted DVD images 
    if [ -z "$FILES" ]; then
        printf "There is no \"Mac OS X Install *\" in /Volumes\n" > $DEBUG
    else
        for FILE in $FILES; do
            XML="$FILE/System/Library/CoreServices/SystemVersion.plist"
            # there are also Disk 2 and Disk 3 CDs that don't contain
            # an installer
            if [ -f "$XML" ]; then
                # print the app folder
                printf "%s:\n" "$FILE"
                print_xml_info "$XML"
            else
                printf "\"$FILE\" found, but it does not contain an installer\n" > $DEBUG
            fi
        done
    fi
fi

# Restore the IFS
IFS=$IFS_BACKUP

